### ISSUE TITLE
Template Gallery Feedback

### ISSUE THREAD

**Issue by delsonting** [forwardsi/GTM_Templates_Newsletter_Floater#1]
Your template has been approved and should be available in the template gallery shortly. Two recommendations:

1) Documentation link is broken: https://github.com/forwardsi/WebNotificationsLibrary

2) URI Encode data.key using [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) function on line 236

> const scriptUrl = 'https://webapps.move.forward.si/webnotifications?key=' + data.key + '&initializedViaParams=true';

**Comment by zigcccc** [comment]
@delsonting will fix ASAP

**Comment by zigcccc** [comment]
Fixed with commit https://github.com/forwardsi/GTM_Templates_Newsletter_Floater/commit/dab03ba5af5a0ad57abce2ad65cee6803a940a54.
